### PR TITLE
Remove reference to G+

### PR DESCRIPTION
**Pull request by edent**
RIP Google+!

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description?  |  This service no longer uses Google+
| Type?         |  Documentation
| BC breaks?    |  no
| Deprecations? |  no
| Fixed ticket? | N/A
| How to test?  | Should no longer display info about G+

### CODE REVIEW

**Review by matks — DISMISSED** [review]
Nice catch

**Comment by matks** [comment]
I changed branch from `master` to `dev` but now we have an unwanted commit. Could you rebase your PR to remove it or recreate the PR using `dev` branch as origin? 😉 

Source https://devdocs.prestashop.com/8/project/maintainers-guide/release-a-native-ps-module/#release-process

**Comment by kpodemski** [comment]
We need to do more changes related to texts in this module. For example description in the php file is completely different and says something about Instagram 🙈

**Review by NeOMakinG — APPROVED** [review]

**Review by PierreRambaud — CHANGES_REQUESTED** [review]
Hi and thanks for your contribution.
Would you rebase and squash your pull request please?

**Comment by matks** [comment]
Hello, it seems this PR is now stale.

I close this PR, following our [review guidelines](https://devdocs.prestashop.com/1.7/project/maintainers-guide/reviewing-pull-requests/) "Pull Requests may be closed after 30 days of inactivity".

If however you are still interested in it, please ping us 😉  we can reopen.

Thank you for your contribution.

**Pull request closed without merging**
