### PR TITLE
Remove Google+

### PR DESCRIPTION
**Pull request by micka-fdz**

### CODE REVIEW

**Review by PierreRambaud — APPROVED** [review]

**Comment by Progi1984** [comment]
Thanks @micka-fdz

**Comment by jf-viguier** [comment]
do you have plans to make a release ? We have to patch for google+

**Comment by PierreRambaud** [comment]
@jf-viguier It will be done as soon as possible.

**Comment by micka-fdz** [comment]
Hello, any news about a release? There is a lot of PRs on hold.

**Pull request merged**
