### PR TITLE
Bump to version 2.1.0

### PR DESCRIPTION
**Pull request by PierreRambaud**

### CODE REVIEW

**Comment by matks** [comment]
@PierreRambaud Are waiting for something for this PR ? Else shall we ask QA validation ?

**Comment by matks** [comment]
@PierreRambaud I suggest merging https://github.com/PrestaShop/ps_sharebuttons/pull/32 first

**Review by matks — APPROVED** [review]

**Comment by PierreRambaud** [comment]
@matks There is nothing to test here :wink:

**Comment by matks** [comment]
Then QA test will happen on PR merging `dev` into `master` ?

**Comment by PierreRambaud** [comment]
Yep :+1:

**Comment by matks** [comment]
Thank you @PierreRambaud

**Pull request merged**
