### PR TITLE
Uninstall module used on PS 1.6 before using this one

### PR DESCRIPTION
**Pull request by Quetzacoalt91**

### CODE REVIEW

**Review by PierreRambaud — DISMISSED** [review]

**Comment by Progi1984** [comment]
Hello @Quetzacoalt91 , thanks for your contribution, would you mind to rebase your pull request? Thanks

**Comment by Quetzacoalt91** [comment]
Here you go!

**Review by Progi1984 — APPROVED** [review]

**Review by matthieu-rolland — APPROVED** [review]

**Comment by sarahdib** [comment]
The module 1.6 isn't uninstall

**Comment by atomiix** [comment]
With **socialsharing** installed, **ps_sharebuttons** not installed:
Capture d’écran 2021-02-17 à 17 32 39

After installing **ps_sharebuttons**:
Capture d’écran 2021-02-17 à 17 33 14

This is QA ✔️

**Pull request merged**
