### PR TITLE
Use Organization Build Release Github Action

### PR DESCRIPTION
**Pull request by atomiix**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description?  | Use Organization Build Release Github Action
| Type?         | improvement
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | 
| How to test?  | CI should be green

### CODE REVIEW

**Review by kpodemski — APPROVED** [review]

**Comment by kpodemski** [comment]
@atomiix I think this repo requires two approvals, which seems wrong, for the modules it should be 1. Am I right?

**Comment by atomiix** [comment]
@kpodemski I just checked the settings and it requires only 1 approve 🤔

**Comment by kpodemski** [comment]
@atomiix well, I can't merge it

@matks, I think you've solved such an issue one time?

**Comment by atomiix** [comment]
What about now @kpodemski?

**Review by NeOMakinG — APPROVED** [review]

**Pull request merged**
